### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JacRossiter** [DotBow/Blender-Sticky-UV-Editor-Add-on#2]
Absolutely love this functionality, I think there's huge promise is this concept. Would it be possible to expand functionality to beyond just UVs? For example on the right I would like to enable/disable the properties panel and on the bottom the material shader editor. I see no reason why it couldn't also support multiple panels on one side, like on the right side having outline and properties ans panels that can be opened. Just some ideas. I could have together something that works for me but it will be a disgusting code mess that will probably stop working in 6 months aha

**Comment by DotBow** [comment]
> Absolutely love this functionality, I think there's huge promise is this concept. Would it be possible to expand functionality to beyond just UVs? For example on the right I would like to enable/disable the properties panel and on the bottom the material shader editor. I see no reason why it couldn't also support multiple panels on one side, like on the right side having outline and properties ans panels that can be opened. Just some ideas. I could have together something that works for me but it will be a disgusting code mess that will probably stop working in 6 months aha

Hi! Thanks for suggestion and sorry for such late response.
Your ideas is beyond add-on purpose, so there is no way it will land in Sticky UV Editor.
Also, from the code perspective building such a complex layout management is barely possible because of the way Blender works. It is better to use workspaces and utilize `ctrl+space`.
